name: first job
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo command
        run: echo "Hello World "
      - name: Run multiline script
        run: |
            python3 --version
            npm -v 
