name: Action job
on: [push]

jobs:
  run-github-actions-cmd:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: baljeetsingh
      - name: Time printing actions
        run: echo "${{steps.greet.outputs.time}}"