name: first job
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo command
        run: echo "Hello World "
      - name: Run multiline script
        run: |
            python3 --version
            npm -v
      - name: Run Python script
        run: |
            import os
            print(os.getcwd())
        shell: python
  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: Running Directory location
        run: get-location
      - name: Bash directry
        run: pwd
        shell: bash